ewasm/hera

src/eei.h
=> Fix InternalErrorException to derive off std::exception

src/eei.cpp, src/eei.h
Fixes #3 - helper functions for interface methods
also cleaned up the commit history
=> Reworked helper fns

src/eei.cpp
=> EEI: interface method "getCaller"

src/eei.cpp
=> EEI: interface method "getCallValue"

src/eei.cpp, src/eei.h, src/hera.cpp
=> EEI: interface method "codeCopy"

src/eei.cpp
=> EEI: interface method "getBlockCoinbase"

src/eei.cpp
=> EEI: interface method "getBlockDifficulty"

evm.h, src/hera.cpp
Part of https://github.com/ethereum/cpp-ethereum/issues/4763
=> Abort execution early with EVM_UNSUPPORTED_CODE_TYPE

src/eei.cpp
=> EEI: interface method getTxGasPrice

src/eei.cpp
=> EEI: interface method getBlockNumber

src/eei.cpp
=> EEI: interface method "getTxOrigin"

README.md, src/eei.cpp, src/eei.h
=> Implement debug namespace

src/eei.h
=> EEI: execution result should be a reference

src/eei.cpp
=> EEI: enforce staticCall

cmake/ProjectBinaryen.cmake
Another fix. I realized we are not linking hera lib with anything here...
=> ProjectBinaryen: Fix paths to libraries

src/eei.cpp
See https://github.com/ewasm/design/issues/70
=> EEI: change call to not return result data

src/eei.cpp
=> EEI: Update call*/create return codes

src/hera.cpp
Reflects changes in https://github.com/ewasm/evm2wasm/pull/189
=> change evm2wasm invocation to reflect new CLI parameters

src/eei.cpp
(probably) fixes https://github.com/ewasm/hera/issues/137 https://github.com/ewasm/hera/issues/129
=> Zero-fill return data  buffer correctly 

README.md, src/eei.cpp
=> Implement evmTrace

circle.yml, scripts/tests.sh
=> Build and run state tests on circleci

cmake/ProjectBinaryen.cmake, src/shell-interface.h
hopefully this works, lmao
Fixes #142
=> Update Binaryen to 1.37.35

src/hera.cpp
=>  Fix ifdef for evm2wasm.js EVM-C option

circle.yml
=> CI: Use cpp-ethereum with EVMC status code passthrough

README.md, src/hera.cpp
Fixes #181 
needs ci to be fixed for tests to run #193
=> Metering as a runtime option

README.md, circle.yml
=> Circle CI: Build Hera as a shared lib in one of the jobs

src/eei.cpp, src/exceptions.h
Depends on #201. Closes #188.
This is the first in introducing more granular exception and a nice way to have assertions for them.
=> Add ensure condition

src/eei.cpp
=> Assert argument counts in the EEI

src/eei.cpp, src/hera.cpp
=>  Return EVM_INTERNAL_ERROR for InternalErrorException

src/eei.cpp, src/eei.h, src/hera.cpp
=>  Disable interface gas metering if evm2wasm is used

src/eei.cpp, src/eei.h, src/hera.cpp, src/vm.cpp, src/vm.h
Part II of the wasm engine abstraction layer. Merges into said PR.
=> [WIP] WASM engine-agnostic EEI host functions

src/hera.cpp
=> Always pass original input code to the interface

src/eei.cpp, src/eei.h
=> Do not fully disable metering when interface metering is disabled

src/hera.cpp
=> Enable interface metering on evm2wasm

src/eei.h
=> Consider wasm traps as non-internal errors

README.md
See if Hera is fucked, right on the front page!
=> Add CI badge for Hera

src/hera.cpp
=> Properly handle rejecting EVM bytecode

src/eei.cpp
building on https://github.com/ewasm/hera/pull/217 for the test case `stCallCodes/callcall_00` with evm2wasm.
=> Add proper gas stipend and 63/64th rules for CALL*

src/hera.cpp
=> Validate basic ECI rules

src/eei.cpp
=> Ensure that memory for call/create payload is properly kept

circle.yml, src/hera.cpp
=> Update evm2wasm submodule to b2b8bef

.gitignore
Also ignore swap files since this was getting bothersome.
=> Add more entries to .gitignore

LICENSE, README.md, src/CMakeLists.txt, src/eei.cpp, src/eei.h, src/exceptions.h, src/hera.cpp, src/hera.h
=> Relicense Hera to Apache 2.0 (Finally!)

src/eei.cpp, src/eei.h
This simplifies the code significantly.
=> Refactor ensureSenderBalance into enoughSenderBalanceFor

README.md, src/hera.cpp
=> Introduce hera_wasm_engine enum

src/eei.cpp, src/eei.h
Extracted from #148.
Part of #156.
=> Add memory helpers to aid abstraction

src/eei.cpp
Implements https://github.com/ewasm/design/pull/76. Closes #111.
=> getBlockhash() to signal success or failure

src/eei.cpp
=> Refactor call* handling for readability

src/eei.cpp
Part of #156.
Inspired by #148.
Helps with #294.
=> Refactor topic handling in log()

CMakeLists.txt, circle.yml
Why is the debug version of shared library failing?
=> Circle CI: Use Aleth 1.4.0rc1 for testing

src/eei.cpp
=> Add proper assertion for ewasm-incompatible balances coming from the client

src/eei.cpp, src/eei.h
=> Add 'Reverse' suffix to loadMemory/storeMemory with byte pointer

CMakeLists.txt, src/CMakeLists.txt, src/hera.cpp
Resolves https://github.com/ewasm/hera/issues/276.
=> Hera version and build info

src/shell-interface.h
=> Fix the signedness in ShellInterface::init

src/hera.cpp
For use in calling and defining system contracts
=> Add constants for system contract addresses

src/eei.cpp, src/eei.h
Part of #318.
Part of https://github.com/ewasm/design/pull/105
=> Do not consider addresses as numbers (do not change byteorder)

src/eei.cpp, src/eei.h
=> Consider most of the 256-bit values as bytes32 and keep difficulty as uint256

circle.yml
=> Circle CI: Upgrade Aleth to 1.4.0rc4

src/eei.cpp, src/eei.h, src/hera.cpp
Part of #156.
Heavily based on #148.
=> Split Binaryen implementation and the core EthereumInterface

circle.yml
=> CircleCI: run evm2wasm tests with shared Hera

src/helpers.cpp, src/helpers.h, src/hera.cpp
=> Clean up preloading system contracts code

src/binaryen.cpp, src/binaryen.h, src/hera.cpp, src/wabt.cpp, src/wabt.h
=> Use WasmEngine factory method to simplify the engine creation

src/hera.cpp
=> Final cleanup touches to contract preloading

circle.yml, src/wabt.cpp, src/wabt.h
=> Implement storageStore/storageLoad/getGasLeft/getCallValue in wabt

.bumpversion.cfg, CMakeLists.txt
=> Add bumpversion config

circle.yml, src/hera.cpp
=> Add lint step with running codespell

src/wavm.cpp, src/wavm.h
Idea from https://github.com/ewasm/hera/pull/394#issuecomment-421353465
=> Split wavm code for the ability of running GC

src/binaryen.cpp, src/wabt.cpp
=> Do not import the wabt/binaryen namespaces

cmake/ProjectBinaryen.cmake
=> binaryen: Fix ExternalProject build on RedHat based Linuxes

src/binaryen.cpp, src/binaryen.h
=> Split verifyContract out in BinaryenEngine

src/binaryen.cpp, src/binaryen.h, src/eei.h, src/hera.cpp, src/wabt.h, src/wavm.h
Depends on https://github.com/ewasm/tests/pull/91
=> Run verifyContract on the bytecode returning during deployment

.bumpversion.cfg, CMakeLists.txt
Same rules as https://github.com/ethereum/aleth/issues/5276
=> Update bumpversion config, set version to 0.1.0-alpha.0

src/eei.cpp
This fixes everything, but `call` and `storageStore`.
=> Charge interface gas early (part 1)

src/eei.cpp
=> Charge early the minimum cost for storageStore

src/eei.cpp
=> Move depth and sender balance checks earlier in eeiCall

src/eei.cpp
=> Revert on calls from addresses with 128bit+ balances

CMakeLists.txt, README.md, test/CMakeLists.txt, test/fuzzing/CMakeLists.txt, test/fuzzing/fuzzer.cpp
=> hera-fuzzer

circle.yml
=> CI: More macos work

src/wabt.cpp
=> Remove redundant usage of wabt:: namespace

cmake/ProjectWabt.cmake, src/eei.h, src/wabt.cpp
1.0.6 gives us two benefits (amongst others):
- https://github.com/WebAssembly/wabt/pull/886: fixes host trapping
- https://github.com/WebAssembly/wabt/pull/882: speeds up the build process
=> Update to wabt 1.0.6

lgtm.yml
=> Add configuration for lgtm

circle.yml, src/wabt.cpp, src/wabt.h
Work in progress. Code is in place. Only tested some of the eei methods. Still needs confirmation that it passes all the tests. Feel free to take over if you need this done asap.
=> update wabt with remaining eei methods

cmake/ProjectWAVM.cmake, src/wavm.cpp
=> Upgrade wavm to newer version

README.md
=> Mention support for wabt is complete in README

src/eei.cpp, src/eei.h
=> Add call depth level to debugging messages

src/wavm.cpp
=> Some smaller cleanups to WAVM

circle.yml
=> Run returnVeryLong/revertVeryLong on CI for wavm

src/wavm.cpp
=> wavm: Handle WavmEthereumInterface lifetime by RAII

README.md, circle.yml, src/binaryen.cpp, src/eei.cpp, src/eei.h, src/hera.cpp, src/wabt.cpp, src/wavm.cpp
=> Benchmarking instrumentation

src/eei.cpp, src/eei.h
=> Use EVMC HostInterface 

src/eei.cpp, src/eei.h, src/helpers.cpp, src/helpers.h, src/hera.cpp, src/shell-interface.h, src/wabt.cpp
Fixes some includes after #484.
=> Clean up includes

CMakeLists.txt, cmake/Hunter/init.cmake, src/CMakeLists.txt
It upgrades Hunter and enables it by default. The intx 0.2 is added as the Hunter package.
=> Add intx as Hunter package

README.md
See release notes: https://github.com/ewasm/hera/releases/tag/v0.3.0
=> Update readme to EVMCv7 (as of v0.3.0)
