ewasm/hera

src/eei.cpp

EEI: interface method "getCodeSize"

---

src/eei.cpp

EEI: interface method "getBlockGasLimit"

---

src/eei.cpp

EEI: interface method getBlockTimestamp

---

src/eei.cpp

The half of returned value was not initialized.

Fix loadUint128()

---

src/eei.cpp

Fix bug where an attempt is made to load input data with zero length

 EEI: avoid returning a pointer for msg.input if msg.input_size is 0

---

src/eei.cpp

Memory ops will now simply report this with HERA_DEBUG.

Remove asserts stopping zero-length memory loads/stores

---

src/eei.cpp

1. Print out all args
2. Fix order of memory offsets

Two small fixes to returnDataCopy

---

cmake/ProjectBinaryen.cmake

When building `cpp-ethereum` on Fedora 27, `libbinaryen.a` is generated in `deps/lib64`, not `deps/lib`.
Same type of problem as there was with `MPIR` (https://github.com/ethereum/cpp-ethereum/issues/4159).

Fix cpp-ethereum build due to libbinaryen.a not found

---

src/eei.cpp

Returns false when an element different than zero is found.

fix isZeroUint256 helper function

---

src/hera.h

This is so that hera can be being dynamically loaded in the future.

Export hera_create() so that it can evenetually be loaded dynamically

---

src/hera.cpp

When running transcompiled EVM code (from evm2wasm.js), individual bytes are not correctly padded when storing to a temp file before transcompilation.  The result is that the bytecode is mangled.
This PR fixes the issue.

Fix issue with EVM bytecode mangling

---

src/eei.cpp

Fixes an issue with the stack trace interface method.

make sure the first item in the stack is printed

---

src/hera.cpp

Fix for EVM bytecode mangling issue that wasn't handled in https://github.com/ewasm/hera/pull/160

Zero-pad every byte in EVM string, not entire string

---

src/hera.cpp

When the char array passed to `mktemp()` is missing a null-terminator, it fails in some environments (on circleCI servers).
replaces https://github.com/ewasm/hera/pull/175

mktemp null-terminator fix and evm2wasm.js debug prints

---

src/eei.cpp

Likely caused by
https://github.com/ewasm/hera/commit/f16e8ed90a404579a86a1e07f2ec1aff43c826a0.
Per @chfast: I think it was my change, but Linux has different C++
standard lib and array is included by some other header.

Fix missing array import

---

src/eei.cpp
src/eei.h

Ensure that balance/value is checked for as 128 bits and not 64 bits

---

src/eei.cpp

They should be loaded into the second half of the `evmc_uint256be`.

 loadUint128 to properly write into the right part of evmc_uint256be

---

README.md
circle.yml
src/CMakeLists.txt

Remove obsolete metering option from cmake and circleci

---

CMakeLists.txt

cpp-ethereum builds with this flag and sometimes fails build even when hera appears to build fine for this reason.

Add -Werror to CFLAGS

---

src/eei.cpp
src/eei.h

portability of this fix requires investigation
Closes #245. Fixes #190.

Use int128 compiler extension for ensureSenderBalance

---

src/eei.cpp

Requires https://github.com/ewasm/tests/pull/44
Take base gas before doing 63/64 calc and refund remaining gas after call.
Also includes a bunch more gas-related debug output and a new debug flag to keep evm2wasm output files around for debugging.

Fix gas related to CREATE

---

README.md

Had a 404 in the README.md. 
Fixed with ewasm/evm2wasm reference

- evm2wasm link fix

---

src/eei.cpp

Use offset 0 when reading from newly-created buffer. Otherwise we get out-of-bounds errors when we shouldn't.

Fix storeMemory logic for extCodeCopy

---

src/eei.cpp

Per https://github.com/ewasm/tests/issues/34 and https://github.com/ewasm/hera/pull/256#issuecomment-408501827 we want codecopy and extcodecopy to trap on OOB rather than zero padding.

Trap OOB on externalcodecopy

---

src/hera.cpp

Most of the consumers will be non C++ and as such wouldn't be able to
properly handle exceptions, better to terminate for uncaught exceptions.
Follow up of #268.

Mark all the publicly exported functions as noexcept

---

CMakeLists.txt
README.md
circle.yml
cmake/ProjectWAVM.cmake
cmake/patch_wavm.sh
src/CMakeLists.txt

This adds -DHERA_WAVM option what for now will build WAVM and link hera with it. Because Hera does not uses WAVM it will not do anything useful, but we can check if the build works.
Also the `HERA_WAVM=1` macro is predefined for build with WAVM.
This depends on LLVM 6.0 so you have to install libllvm-6.0-dev. See http://apt.llvm.org.
The WAVM produces a number of libraries. In this PR only the libruntime is used, probably more is going to be needed when we start using WAVM.

 CMake: Add option to build with WAVM

---

src/eei.cpp

If there is insufficient gas for the value being sent with the CALL,
rather than throwing an OOG exception, the operation should just fail.
Fixes an issue detected in test GeneralStateTests/stCallCreateCallCodeTest/callWithHighValue

Fix gas semantics for CALL and CALLCODE

---

src/eei.cpp

Depends on #280.
This matches how aleth-interpreter works.

Ensure that call depth is not exceeded in call*/create

---

src/eei.cpp
src/eei.h

loadMemory was only checking for integer overflow/negative length. Also
check that we don't attempt to copy from beyond the end of memory. Also
perform the same check before attempting to resize a vector larger than
memory.
Tests in https://github.com/ewasm/tests/pull/57

Check for out of bounds source on memory copy

---

src/eei.cpp
src/eei.h

It also prepares it for VM abstraction.
Part of #156.

Introduce EEICallKind within the call* handler to simplify code

---

.gitmodules
CMakeLists.txt
circle.yml
codecov.yml

Code Coverage

---

src/eei.cpp

https://ethereum.github.io/yellowpaper/paper.pdf - appendix H shows that the cost for returndatacopy has changed to be more in the style of *copy.

Fix EVM compatibility in gas charges for ReturnDataCopy

---

src/eei.cpp

Fix warnings for signedness

---

CMakeLists.txt

This mitigates the current build problem. Fixes #330.

CMake: Set RelWithDebInfo as the default build type

---

src/eei.cpp

Counterpart of https://github.com/ewasm/design/pull/120

Rename externalBalance to getExternalBalance

---

src/eei.cpp
src/eei.h
src/hera.cpp

Clean up the handling of gas (use int64_t only)

---

CMakeLists.txt
src/eei.cpp

CMake: enable -Wsign-conversion

---

src/eei.cpp
src/eei.h

Part of #156.
Inspired by #148.

Extract EEI methods from within callImport (call, create, selfDestruct, returnDataCopy)

---

src/eei.cpp

Consider blockhash as bytes32 and not uint256

---

src/hera.cpp

Default case is not needed when all enum values are handled. In case of mistake you get error like this
```
/home/builder/project/src/hera.cpp: In function 'evmc_result {anonymous}::hera_execute(evmc_instance*, evmc_context*, evmc_revision, const evmc_message*, const uint8_t*, size_t)':
/home/builder/project/src/hera.cpp:281:14: error: enumeration value 'reject' not handled in switch [-Werror=switch]
switch (hera->evm_mode) {
^
```
CI protects it: https://circleci.com/gh/ewasm/hera/4624

Simplify switch statements

---

circle.yml

This works locally too:
```
$ evmc/test/evmc-vmtester src/libhera.dylib 
Testing src/libhera.dylib
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from evmc_vm_test
[ RUN      ] evmc_vm_test.abi_version_match
[       OK ] evmc_vm_test.abi_version_match (0 ms)
[ RUN      ] evmc_vm_test.set_option_unknown
[       OK ] evmc_vm_test.set_option_unknown (0 ms)
[ RUN      ] evmc_vm_test.set_option_empty_value
[       OK ] evmc_vm_test.set_option_empty_value (0 ms)
[ RUN      ] evmc_vm_test.name
[       OK ] evmc_vm_test.name (0 ms)
[ RUN      ] evmc_vm_test.version
[       OK ] evmc_vm_test.version (0 ms)
[ RUN      ] evmc_vm_test.set_tracer
[       OK ] evmc_vm_test.set_tracer (0 ms)
[----------] 6 tests from evmc_vm_test (0 ms …
```

Run evmc-vmtester on the built Hera shared library

---

src/binaryen.h
src/eei.h
src/hera.cpp

Keep the Wasm Engine by owned pointer in the Hera instance. Pointer allows future polymorphic behavior.
Fixes #372.

Move WasmEngine to Hera instance

---

README.md
src/helpers.cpp
src/helpers.h
src/hera.cpp

Closes #288 
Syntax: `--evmc sys:<address or alias>=<filepath>`
Hex address must be formatted with a leading `0x` and must be 40 characters long (all nibbles must be explicitly specified, including leading zeroes).

Add option to preload system contracts from file before execution

---

src/eei.cpp
src/eei.h

Also independently discovered by @jakelang.

Query evmc_tx_context once in each execution

---

CMakeLists.txt

Closes #373 
This adds `-Wswitch-enum` flag for Hera library.
The `-Wimplicit-fallthrough` was added earlier with `cable_configure_compiler()`.
Also it updates the Cable to avoid the "old version" warning.

CMake: Compiler flags

---

README.md
circle.yml
cmake/ProjectWAVM.cmake
src/CMakeLists.txt
src/eei.h
src/hera.cpp
src/wavm.cpp
src/wavm.h

Early version of wavm execution in Hera. Should compile with `cmake -DHERA_WAVM=ON`. May need some work.
Closes #158.
Depends on #401.

Initial support for WAVM as an engine

---

CMakeLists.txt
circle.yml

This change sets the BUILD_SHARED_LIBS flag to ON by default.
Closes https://github.com/ewasm/hera/issues/413.

CMake: Build shared libraries by default

---

src/hera.cpp

These are provided by EVMC 6.0.0
Fixes #443.

Remove evmc_address comparator helpers

---

cmake/ProjectWAVM.cmake
cmake/ProjectWabt.cmake

For binaryen + wabt:
```
nm -Cg src/libhera.so | wc -l 
readelf -r src/libhera.so | wc -l
```
Before: 9852 10831
After: 3993 6510

CMake: Hide symbols from wasm engines included

---

README.md
src/hera.cpp

This PR adds runevm as a system contract. I wanted to be able to test runevm via `testeth`, and made these changes to facilitate that. Not sure if this is something that you'd want merged.
Just now when I wanted to push my branch name conflicted with https://github.com/ewasm/hera/tree/runevm and I found this commit https://github.com/ewasm/hera/commit/866e12c90f644d834eb68836c700ba82c3d90267 (Update: just saw the PR https://github.com/ewasm/hera/pull/375) which would have saved me a day! :)
Three points about the PR:
- I couldn't get `context->host->call` to work, and directly use the `WasmEngine` to call runevm.
- When the runevm instance was being instantiated it would cause out-of-bounds memory access so I added the `module.memory.initial = 20` to avoid that. Not sure how to properly …

Initial support for runevm contract

---

circle.yml

Depends on #288, #513. Depends on releasing [runevm](https://github.com/axic/runevm).

Run evm2wasm tests using runevm

---

lgtm.yml

Enable wavm on lgtm

---

src/wavm.cpp

`memoryRef` code is [here](https://github.com/WAVM/WAVM/blob/fa5434e03efbc2154ecf4aafede169da76a4da40/Include/Runtime/Runtime.h#L294) in WAVM.

Use memoryRef and not memoryArrayPtr for single elements in WAVM 
